FROM python:3.6.0-slim

WORKDIR /app
ADD . /app

RUN apt-get update && \
    apt-get install -y build-essential &&\
    pip install -r /app/requirements.txt

ENV POST_DATABASE_HOST post_db
ENV POST_DATABASE posts

ENTRYPOINT ["python3", "post_app.py"]
